# Generated by Django 2.0 on 2018-05-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.BigIntegerField(verbose_name='Subscriber telephone number')),
                ('period', models.DateField(verbose_name='Period of the telephone bill')),
                ('destination', models.BigIntegerField(verbose_name='Telephone number that received the call')),
                ('start_date', models.DateField(verbose_name='Start date of the telephone bill')),
                ('start_time', models.DateTimeField(verbose_name='Start time of the telephone bill')),
                ('duration', models.DurationField(verbose_name='Duration of the telephone call')),
                ('price', models.DecimalField(decimal_places=2, max_digits=99, verbose_name='Price of the telephone call')),
            ],
            options={
                'verbose_name': 'Telephone bill',
                'verbose_name_plural': 'Telephone bills',
            },
        ),
    ]
